import mongoose from 'mongoose';

const schema = new mongoose.Schema(
  {
    title: {},
    siteName: {},
    description: {},
    messages: [],
    plugins: {},
    data: [],
    settings: {},
    siteActive: { type: Boolean, default: true },
    tax: { type: Boolean, default: true },
    taxAmount: Number,
    defaultLanguage: String,
    factor_shop_name: String,
    factor_shop_site_name: String,
    factor_shop_site_address: String,
    factor_shop_address: String,
    factor_shop_phone: String,
    factor_shop_faxNumber: String,
    factor_shop_postalCode: String,
    factor_shop_submitCode: String,
    factor_shop_internationalCode: String,
    defaultSmsGateway: String,
    defaultBankGateway: String,
    siteActiveMessage: String,
    logo: String,
    header_first: String,
    header_last: String,
    body_first: String,
    body_last: String,
    ADMIN_ROUTE: String,
    ADMIN_URL: String,
    SHOP_URL: String,
    BASE_URL: String,
    ZIBAL_TOKEN: String,
    ZARINPAL_TOKEN: String,
    primaryColor: String,
    secondaryColor: String,
    textColor: String,
    bgColor: String,
    footerBgColor: String,
    activeCategory: [{ type: mongoose.Schema.Types.ObjectId, ref: 'category' }],
    customerStatus: [],
    formStatus: [],
    currency: { type: String, default: 'Toman' },
    dollarPrice: Number,
    derhamPrice: Number,
    sms_welcome: {},
    sms_register: {},
    sms_submitOrderNotPaying: {},
    sms_submitOrderSuccessPaying: {},
    sms_onSendProduct: {},
    sms_onGetProductByCustomer: {},
    sms_submitReview: {},
    sms_onCancel: {},
  },
  { timestamps: true }
);

export default schema;
