version: '3'

services:
  shop:
    image: nodeeweb-shop:0.0.1
    build:
      context: ..
      dockerfile: shop/Dockerfile
    container_name: nodeeweb-shop
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 2m
    networks:
      mongonet:
      webnet:
        aliases:
          - nodeeweb-shop
          - nwi-shop
    env_file:
      - .env.local
    volumes:
      - /var/instances/nwi-shop/shared:/app/shared
      - /var/instances/nwi-shop/logs:/app/logs
      - /var/instances/nwi-shop/public:/app/public

networks:
  mongonet:
    external: true
    name: mongonet
  webnet:
    external: true
    name: webnet
