export const MAXIMUM_NEED_TO_PAY_TRANSACTION = 3;
export const DEFAULT_TRANSACTION_EXP_S = 15 * 60 * 1_000;
export const DEFAULT_APPROACH_TRANSACTION_EXP = 0.75;
export const MAX_PRODUCT_QUANTITY_IN_CART = 100;
export const MAX_PRODUCTS_IN_CART = 100;
