version: '3'

services:
  core:
    image: nodeeweb-core:0.0.3
    build: .
    container_name: nodeeweb-core
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 2m
    networks:
      mongonet:
      webnet:
        aliases:
          - nodeeweb-core
          - nwi-core
    env_file:
      - .env.local
    volumes:
      - /var/instances/core/shared:/app/shared:ro
      - /var/instances/core/public/public_media:/app/public_media:ro
      - /var/instances/core/public/admin:/app/admin:ro
      - /var/instances/core/public/logs:/app/logs:ro

networks:
  mongonet:
    external: true
    name: mongonet
  webnet:
    external: true
    name: webnet
