name: Publish & Deploy front on npm

on:
  push:
    branches:
      - main
      - 'releases/**'
      - dev
    paths:
      - 'front/**'

jobs:
  build:
    name: 'Build Application'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout to repository'
        uses: actions/checkout@v4

      - name: 'Setup nodeJs'
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 'Install yarn'
        run: npm i -g yarn

      - name: Setup node-gyp
        run: yarn global add node-gyp

      - name: 'Install dependencies'
        working-directory: front
        run: yarn

      - name: 'Repository visualizer'
        id: diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          excluded_paths: 'node_modules,build,.storybook,.github'
          output_file: 'front/diagram.svg'
          should_push: false
          root_path: 'front/src/'
          artifact_name: 'diagram'

      - name: 'Build App'
        run: yarn build
        working-directory: front
        env:
          CI: 'false'
          GENERATE_SOURCEMAP: 'false'

      - name: 'Upload build artifact'
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: front/build

  publish-npm:
    needs: build
    name: Publish on npm
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout to repository'
        uses: actions/checkout@v4

      - name: 'Check Branch'
        id: 'check_branch'
        run: |
          if [ $GITHUB_REF_NAME == 'main' ] || [[ $GITHUB_REF_NAME == release/* ]]
          then echo 'IS_PRO=true' >> $GITHUB_OUTPUT
          else echo 'IS_PRO=false' >> $GITHUB_OUTPUT
          fi
      - name: 'Setup nodeJs'
        uses: actions/setup-node@v3
        if: ${{steps.check_branch.outputs.IS_PRO == 'true' }}
        with:
          node-version: 18

      - name: 'Download build artifacts'
        uses: actions/download-artifact@v3
        if: ${{steps.check_branch.outputs.IS_PRO == 'true' }}
        with:
          name: build
          path: front/build

      - name: 'Download diagram artifacts'
        uses: actions/download-artifact@v3
        if: ${{steps.check_branch.outputs.IS_PRO == 'true' }}
        with:
          name: diagram
          path: front/build

      - name: 'Publish'
        working-directory: front
        if: ${{steps.check_branch.outputs.IS_PRO == 'true' }}
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  deploy-server:
    name: 'Deploy on server'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'Download build artifacts'
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: 'Download diagram artifacts'
        uses: actions/download-artifact@v3
        with:
          name: diagram
          path: build

      - name: 'Setup metadata'
        id: setup_metadata
        run: |
          if [ $GITHUB_REF_NAME == 'main' ] || [[ $GITHUB_REF_NAME == release/* ]]
          then 
            echo "TARGET_PATH=/var/instances/nwi-shop/public/front/" >> $GITHUB_OUTPUT
            echo "IS_PRO=true" >> $GITHUB_OUTPUT
          else 
            echo "TARGET_PATH=/var/instances/nwi-shop-dev/public/front/" >> $GITHUB_OUTPUT
            echo "IS_PRO=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: 'FTP to german server'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{secrets.GERMAN_HOST}}
          username: ${{secrets.GERMAN_FTP_USER}}
          password: ${{secrets.GERMAN_FTP_PASS}}
          local-dir: 'build/'
          server-dir: ${{steps.setup_metadata.outputs.TARGET_PATH}}
          timeout: 600000

      - name: 'Chmod on german server'
        uses: appleboy/ssh-action@v1.0.0
        env:
          TARGET_PATH: ${{steps.setup_metadata.outputs.TARGET_PATH}}
          USER_PASS: ${{secrets.GERMAN_FTP_PASS}}
        with:
          host: ${{secrets.GERMAN_HOST}}
          username: ${{secrets.GERMAN_FTP_USER}}
          password: ${{secrets.GERMAN_FTP_PASS}}
          envs: TARGET_PATH,USER_PASS
          script_stop: true
          script: |
            echo $USER_PASS | sudo -S chmod -R 755 $TARGET_PATH

      # - name: 'FTP to iran server'
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      #   if: ${{steps.setup_metadata.outputs.IS_PRO == 'true'}}
      #   with:
      #     server: ${{secrets.IRAN_HOST}}
      #     username: ${{secrets.IRAN_FTP_USER}}
      #     password: ${{secrets.IRAN_FTP_PASS}}
      #     local-dir: 'build/'
      #     server-dir: ${{steps.setup_metadata.outputs.TARGET_PATH}}
      #     timeout: 600000

      - name: 'SSH on iran server'
        uses: appleboy/ssh-action@v1.0.0
        env:
          TARGET_PATH: ${{steps.setup_metadata.outputs.TARGET_PATH}}
          USER_PASS: ${{secrets.IRAN_FTP_PASS}}
          RUN_ID: ${{github.run_id}}
          REPO_NAME: ${{github.repository}}
          ARTIFACT_NAME: build
        with:
          host: ${{secrets.IRAN_HOST}}
          username: ${{secrets.IRAN_FTP_USER}}
          password: ${{secrets.IRAN_FTP_PASS}}
          envs: TARGET_PATH,USER_PASS,RUN_ID,REPO_NAME,ACTIONS_RUNTIME_TOKEN,ACTIONS_RUNTIME_URL,GITHUB_RUN_ID,OUTPUT_PATH,ARTIFACT_NAME
          script_stop: true
          script: /download-artifact.sh

  cleanup:
    name: Cleanup actions
    needs:
      - publish-npm
      - deploy-server
    runs-on: ubuntu-latest
    steps:
      - name: 'Remove build artifacts'
        uses: geekyeggo/delete-artifact@v2
        with:
          name: |
            build
            diagram
