name: Publish front on npm

on:
  push:
    branches:
      - main
      - 'releases/**'
    paths:
      - 'front/**'

jobs:
  build:
    name: 'Build Application'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout to repository'
        uses: actions/checkout@v4

      - name: 'Setup nodeJs'
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 'Install yarn'
        run: npm i -g yarn

      - name: Setup node-gyp
        run: yarn global add node-gyp

      - name: 'Install dependencies'
        working-directory: front
        run: yarn

      - name: 'Repository visualizer'
        id: diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          excluded_paths: 'node_modules,build,.storybook,.github'
          output_file: 'public/diagram.svg'
          should_push: false
          root_path: 'front/src/'
          artifact_name: 'diagram'

      - name: 'Build App'
        run: yarn build
        working-directory: front
        env:
          CI: 'false'
          GENERATE_SOURCEMAP: 'false'

      - name: 'Upload build artifact'
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: front/build

  publish-npm:
    needs: build
    name: Publish on npm
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout to repository'
        uses: actions/checkout@v4

      - name: 'Setup nodeJs'
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 'Download build artifacts'
        uses: actions/download-artifact@v3
        with:
          name: build
          path: front/build

      - name: 'Download diagram artifacts'
        uses: actions/download-artifact@v3
        with:
          name: diagram
          path: front/build

      - name: 'Publish'
        working-directory: front
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  cleanup:
    name: Cleanup actions
    needs:
      - publish-npm
    runs-on: ubuntu-latest
    steps:
      - name: 'Remove build artifacts'
        uses: geekyeggo/delete-artifact@v2
        with:
          name: |
            build
            diagram
