name: Front Build

on:
  pull_request:
    branches:
      - theme-setting
      - main
      - 'releases/**'
    paths:
      - 'front/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 'Install'
        working-directory: ./front
        run: npm i --legacy-peer-deps
      - name: 'Build'
        working-directory: ./front
        run: npm run build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: 'Publish'
        working-directory: ./front
        run: npm run publish

        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
