name: Front Build

on:
  push:
    branches:
      - releases/**
    paths:
      - 'front/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cd front
      - run: npm i --legacy-peer-deps
      - run: npm run build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
